In [1]:
import numpy as np
import time

## Vector creation

In [2]:
a=np.zeros(4)
print(f'np.zeros(4) = {a}, a shape={a.shape},a datatype ={a.dtype}')
a=np.zeros(4,)
print(f'np.zeros(4,) = {a}, a shape={a.shape},a datatype ={a.dtype}')
a=np.random.random_sample(4)
print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")



np.zeros(4) = [0. 0. 0. 0.], a shape=(4,),a datatype =float64
np.zeros(4,) = [0. 0. 0. 0.], a shape=(4,),a datatype =float64
np.random.random_sample(4): a = [0.60881736 0.40421179 0.76873545 0.94562945], a shape = (4,), a data type = float64


In [3]:
a=np.arange(4.)
print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a=np.random.rand(4)
print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.):     a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.23804321 0.07700432 0.96506588 0.20794439], a shape = (4,), a data type = float64


In [4]:
a=np.array([5,4,3,2])
print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a= np.array([5,4.,3,2])
print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int32
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


## Indexing

In [5]:
a=np.arange(10)
print(a)
print(f"a[2].shape: {a[2].shape} a[2]  = {a[2]}, Accessing an element returns a scalar")
print(f'a[-1]: {a[-1]}')

try:
    a[10]
except Exception as e:
    print(e)


[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2]  = 2, Accessing an element returns a scalar
a[-1]: 9
index 10 is out of bounds for axis 0 with size 10


## Slicing

In [6]:
a=np.arange(10)
print(f"a        = {a}")     
c=a[2:7:1]
print("a[2:7:1] = ", c)
c=a[2:7:2]
print("a[2:7:2] = ", c)
c=a[3:]
print("a[3:]    = ", c)
c=a[:3]
print("a[:3]    = ", c)
c=a[:]
print("a[:]     = ", c)

a        = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


## Single vector operation

In [7]:
a=np.array([1,2,3,4])
print(f"a             : {a}")
b=-a
print(f"b = -a        : {b}")
b=np.sum(a)
print(f"b = np.sum(a) : {b}")
b=np.mean(a)
print(f"b = np.mean(a): {b}")
b=a**2
print(f"b = a**2      : {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]


## Vector Vector element wise opeartion

In [8]:
a=np.array([1,2,3,4])
b=np.array([-1,-2,3,4])
print(f"Binary operators work element wise: {a + b}")

Binary operators work element wise: [0 0 6 8]


In [9]:
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


## Scalar vector operation

In [10]:
a=np.array([1,2,3,4])
b=5*a
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]


## Vector vector dot product

In [11]:

def dot_pro(a,b):
    sum=0
    for i in range(a.shape[0]):
        sum=sum+a[i]*b[i]
    return sum

In [12]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(f"dot_pro(a, b) = {dot_pro(a, b)}")

dot_pro(a, b) = 24


In [13]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
c=np.dot(a,b)
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ")
c = np.dot(b, a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")

NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 
NumPy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = () 


### The need for speed vector vs loop

In [14]:
np.random.seed(1)
a=np.random.rand(10000000)
b=np.random.rand(10000000)
tic=time.time()
dot=np.dot(a,b)
toc=time.time()
print(f'np.dot(a,b) = {c:.4f}')
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")
tic=time.time()
dot=dot_pro(a,b)
toc=time.time()
print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del a
del b

np.dot(a,b) = 24.0000
Vectorized version duration: 23.7772 ms 
my_dot(a, b) =  24.0000
loop version duration: 2333.2276 ms 


In [21]:
x=np.array([[1],[2],[3],[4]])
w=np.array([2])
c=np.dot(x[1],w)

print(f"x[1] has shape {x[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")


x[1] has shape (1,)
w has shape (1,)
c has shape ()


## Matrices

In [19]:
a=np.zeros((1,5))
print(f"a shape = {a.shape}, a = {a}")                     

a=np.zeros((5,1))
print(f"a shape = {a.shape}, a = {a}") 

a=np.random.random_sample((1,1))
print(f"a shape = {a.shape}, a = {a}") 

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (5, 1), a = [[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
a shape = (1, 1), a = [[0.44236513]]


In [24]:
a=np.array([[5],[4],[3]])
print(f" a shape = {a.shape}, np.array: a = {a}")
a=np.array([[5],
           [4],
           [3],
           [2]])
print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape = (4, 1), np.array: a = [[5]
 [4]
 [3]
 [2]]


### Operations on matrices


In [28]:
a=np.arange(6).reshape(-1,2)# The -1 argument tells to compute the number of rows according to the
                            # size of the array and the number of columns
print(f"a.shape: {a.shape}, \na= {a}")
print(f'\n a[2,0].shape: {a[2,0].shape}, a[2,0]={a[2,0]}, type=(a[2,0])={type(a[2,0])}')
print(f'a[2].shape: {a[2].shape},a[2]={a[2]}, type(a[2]) ={type(a[2])}')

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

 a[2,0].shape: (), a[2,0]=4, type=(a[2,0])=<class 'numpy.int32'>
a[2].shape: (2,),a[2]=[4 5], type(a[2]) =<class 'numpy.ndarray'>


In [35]:
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")

a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array
